import { AppState } from './app-state.model';

export const INITIAL_STATE: AppState = {
  users: [
    {
      id: 1,
      name: 'Alice Johnson',
      email: 'alice@example.com',
      role: 'Admin',
      status: 'Active',
      company: 'Acme Corp',
      phone: '+1-555-0101',
      createdAt: '2025-01-15T10:00:00Z',
    },
    {
      id: 2,
      name: 'Bob Smith',
      email: 'bob@example.com',
      role: 'Editor',
      status: 'Active',
      company: 'Globex Inc',
      phone: '+1-555-0102',
      createdAt: '2025-02-20T14:30:00Z',
    },
    {
      id: 3,
      name: 'Carol White',
      email: 'carol@example.com',
      role: 'Viewer',
      status: 'Inactive',
      company: 'Initech',
      phone: '+1-555-0103',
      createdAt: '2025-03-10T09:15:00Z',
    },
    {
      id: 4,
      name: 'David Brown',
      email: 'david@example.com',
      role: 'Editor',
      status: 'Active',
      company: 'Umbrella Ltd',
      phone: '+1-555-0104',
      createdAt: '2025-04-05T16:45:00Z',
    },
    {
      id: 5,
      name: 'Eve Davis',
      email: 'eve@example.com',
      role: 'Viewer',
      status: 'Inactive',
      company: 'Wayne Enterprises',
      phone: '+1-555-0105',
      createdAt: '2025-05-12T11:00:00Z',
    },
  ],
  dashboard: {
    revenue: 24500,
    revenueChange: 12,
    ordersCount: 320,
    ordersChange: 5,
    conversionRate: 3.2,
    conversionChange: 0.4,
  },
  nextUserId: 6,
  currentUserId: 1,
};
