import type { PaletteOptions } from '@mui/material';

/**
 * AUTO-GENERATED by scripts/sync-figma-tokens.mjs
 * Source: variables.json (Figma export)
 * Do NOT edit manually — re-run `npm run sync:figma` instead.
 */

export const lightPalette: PaletteOptions = {
  mode: 'light',

  // --- Intention colors ---
  primary:    { main: '#1976D2', light: '#42A5F5', dark: '#1565C0', contrastText: '#FFFFFF' },
  secondary:  { main: '#9C27B0', light: '#BA68C8', dark: '#7B1FA2', contrastText: '#FFFFFF' },
  error:      { main: '#D32F2F', light: '#EF5350', dark: '#C62828', contrastText: '#FFFFFF' },
  warning:    { main: '#EF6C00', light: '#FF9800', dark: '#E65100', contrastText: '#FFFFFF' },
  info:       { main: '#0288D1', light: '#03A9F4', dark: '#01579B', contrastText: '#FFFFFF' },
  success:    { main: '#2E7D32', light: '#4CAF50', dark: '#1B5E20', contrastText: '#FFFFFF' },

  // --- Surfaces ---
  background: { default: '#FFFFFF', paper: '#FFFFFF' },

  // --- Text ---
  text: { primary: 'rgba(0, 0, 0, 0.87)', secondary: 'rgba(0, 0, 0, 0.6)', disabled: 'rgba(0, 0, 0, 0.38)' },

  // --- Divider ---
  divider: 'rgba(0, 0, 0, 0.12)',

  // --- Action states ---
  action: {
    active:              'rgba(0, 0, 0, 0.56)',
    hover:               'rgba(0, 0, 0, 0.04)',
    selected:            'rgba(0, 0, 0, 0.08)',
    disabled:            'rgba(0, 0, 0, 0.38)',
    disabledBackground:  'rgba(0, 0, 0, 0.12)',
    focus:               'rgba(0, 0, 0, 0.12)',
  },
};

export const darkPalette: PaletteOptions = {
  mode: 'dark',

  // --- Intention colors ---
  primary:    { main: '#90CAF9', light: '#E3F2FD', dark: '#42A5F5', contrastText: 'rgba(0, 0, 0, 0.87)' },
  secondary:  { main: '#CE93D8', light: '#F3E5F5', dark: '#AB47BC', contrastText: 'rgba(0, 0, 0, 0.87)' },
  error:      { main: '#F44336', light: '#E57373', dark: '#D32F2F', contrastText: '#FFFFFF' },
  warning:    { main: '#FFA726', light: '#FFB74D', dark: '#F57C00', contrastText: 'rgba(0, 0, 0, 0.87)' },
  info:       { main: '#29B6F6', light: '#4FC3F7', dark: '#0288D1', contrastText: 'rgba(0, 0, 0, 0.87)' },
  success:    { main: '#66BB6A', light: '#81C784', dark: '#388E3C', contrastText: 'rgba(0, 0, 0, 0.87)' },

  // --- Surfaces ---
  background: { default: '#121212', paper: '#121212' },

  // --- Text ---
  text: { primary: '#FFFFFF', secondary: 'rgba(255, 255, 255, 0.7)', disabled: 'rgba(255, 255, 255, 0.38)' },

  // --- Divider ---
  divider: 'rgba(255, 255, 255, 0.12)',

  // --- Action states ---
  action: {
    active:              'rgba(255, 255, 255, 0.56)',
    hover:               'rgba(255, 255, 255, 0.08)',
    selected:            'rgba(255, 255, 255, 0.16)',
    disabled:            'rgba(255, 255, 255, 0.38)',
    disabledBackground:  'rgba(255, 255, 255, 0.12)',
    focus:               'rgba(255, 255, 255, 0.12)',
  },
};

/** @deprecated Use lightPalette or darkPalette instead */
export const palette = lightPalette;
